# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 7e95cc97194a1959920a8d19c38c9e198d861850
_src_path: gh:lbedner/aegis-stack
_template_version: 0.6.0
ai_backend: memory
ai_framework: pydantic-ai
ai_providers: openai
ai_rag: false
ai_voice: false
author_email: admin@sector-7g.dev
author_name: Your Name
database_engine: postgres
github_username: your-username
include_ai: false
include_auth: true
include_cache: false
include_comms: false
include_database: true
include_redis: true
include_scheduler: true
include_worker: true
project_description: A production-ready async Python application built with Aegis
  Stack
project_name: sector-7g
project_slug: sector-7g
python_version: 3.14
scheduler_backend: postgres
scheduler_with_persistence: true
version: 0.1.0
include_ingress: true
ingress_tls: true
ingress_domain: sector-7g.dev
